# Generated by Django 4.0.5 on 2022-09-19 10:16

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import logistics.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', logistics.models.CICharField(max_length=255, unique=True)),
                ('address', models.TextField(max_length=255)),
                ('state', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', logistics.models.CICharField(max_length=255, unique=True)),
                ('address', models.TextField(max_length=255)),
                ('state', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Destination',
                'verbose_name_plural': 'Destinations',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fuel_required', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_customers', to='logistics.customer')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_destinations', to='logistics.destination')),
            ],
            options={
                'verbose_name': 'Route',
                'verbose_name_plural': 'Routes',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', logistics.models.CICharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z]{2}-[0-9]{2}-[A-Za-z]{2}-[0-9]{4}')])),
                ('purchase_date', models.DateField()),
                ('axle', models.IntegerField(choices=[(12, '12WL'), (14, '14WL'), (16, '16WL'), (22, '22WL')])),
                ('fuel_capacity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('load_capacity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
            },
        ),
        migrations.CreateModel(
            name='Wheel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=255, unique=True)),
                ('purchase_date', models.DateField()),
                ('running_life', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('vehicle_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiclewheels', to='logistics.vehicle')),
            ],
            options={
                'verbose_name': 'Wheel',
                'verbose_name_plural': 'Wheels',
            },
        ),
        migrations.CreateModel(
            name='VehicleMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('vehicle_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_maintenance', to='logistics.vehicle')),
            ],
            options={
                'verbose_name': 'VehicleMaintenance',
                'verbose_name_plural': 'VehicleMaintenances',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('product', models.CharField(max_length=255)),
                ('load', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='driver_trips', to='logistics.driver')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_trips', to='logistics.route')),
                ('vehicle_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_trips', to='logistics.vehicle')),
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Trips',
            },
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('station', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('bill', models.ImageField(blank=True, upload_to='fuel_bills')),
                ('vehicle_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_fuel', to='logistics.vehicle')),
            ],
            options={
                'verbose_name': 'Fuel',
                'verbose_name_plural': 'Fuels',
            },
        ),
    ]
