# Generated by Django 4.0.5 on 2022-09-20 18:24

from django.db import migrations
import logistics.models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_number',
            field=logistics.models.CICharField(max_length=13, unique=True),
        ),
    ]
