# Generated by Django 4.0.5 on 2022-09-20 18:32

import django.core.validators
from django.db import migrations
import logistics.models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_alter_vehicle_vehicle_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_number',
            field=logistics.models.CICharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z]{2}-[0-9]{2}-[A-Za-z]{2}-[0-9]{4}')]),
        ),
    ]
