# Generated by Django 4.0.5 on 2022-09-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_trip_message_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='date',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='trip',
            name='end_date',
            field=models.DateField(blank=True, default=None),
            preserve_default=False,
        ),
    ]
