# Generated by Django 4.0.5 on 2022-09-21 15:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_alter_vehicle_vehicle_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='contact',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{10}')]),
        ),
    ]
