# Generated by Django 4.0.5 on 2022-09-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_alter_trip_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
