# Generated by Django 4.0.5 on 2022-09-22 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_alter_driver_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='route',
        ),
        migrations.AddField(
            model_name='trip',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='customer_trips', to='logistics.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='destination',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='destination_trips', to='logistics.destination'),
            preserve_default=False,
        ),
    ]
