# Generated by Django 4.0.5 on 2022-09-25 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_driver_available_vehicle_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuel',
            name='driver',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='driver_fuel', to='logistics.driver'),
            preserve_default=False,
        ),
    ]
