# Generated by Django 4.0.5 on 2022-09-30 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_fuel_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='destination',
        ),
        migrations.AddField(
            model_name='trip',
            name='route',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='trip_route', to='logistics.route'),
            preserve_default=False,
        ),
    ]
