# Generated by Django 4.0.5 on 2022-09-30 19:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0007_remove_trip_customer_remove_trip_destination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wheel',
            name='purchase_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='wheel',
            name='running_life',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='wheel',
            name='serial_number',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='wheel',
            name='vehicle_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_wheels', to='logistics.vehicle'),
        ),
    ]
