# Generated by Django 4.0.5 on 2022-10-01 20:15

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0009_alter_wheel_purchase_date_alter_wheel_running_life_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wheel',
            name='usage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
