# Generated by Django 4.0.5 on 2022-10-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0010_wheel_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemaintenance',
            name='invoice',
            field=models.ImageField(blank=True, upload_to='maintenance_bills'),
        ),
    ]
